import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import ImageTest from "../components/ImageTest";
import styles from "../styles/Home.module.css";
import vercelImg from "../public/vercel.svg";
import { Button, ButtonBaseProps } from "@mui/material";
// import styled from "@emotion/styled";
import { css } from "@emotion/react";
import tw, { styled } from "twin.macro";

export const getServerSideProps = async () => {
  const res = await fetch("http://localhost:3000/api/hello");
  const data = await res.json();
  if (!data) {
    return {
      notFound: true,
    };
  }
  return {
    props: data,
  };
};

const Name = styled.h1``;

interface IconProps {
  index: number;
}

const Icon = styled.div<IconProps>(({ index }) => [
  tw`
  md:w-1 md:flex-shrink-0 md:mt-20 md:text-blue-500 md:text-5xl
`,
  css`
    position: relative;
    &::before {
      content: "${index}";
      padding: ${index};
    }
  `,
]);

const StyledButton = styled(Button)`
  color: blue;
  background-color: yellow;
`;

const PropedButton = styled(Button)(
  (props: ButtonBaseProps & { textcolor: string }) => ({
    color: props.textcolor,
  })
);

const Home: NextPage<{ name: string }> = ({ name }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <h1 className="text-1xl font-bold ">{name}</h1>

        <div>
          <Button variant="text">Text Button</Button>
          <Button variant="contained">Contained Button</Button>
          <Button variant="outlined">Outlined Button</Button>
        </div>
        <div>
          <StyledButton variant="text">Text Button</StyledButton>
          <StyledButton variant="contained">Contained Button</StyledButton>
          <PropedButton textcolor="red">Outlined Button</PropedButton>
          <Icon index={10}>abb</Icon>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src={vercelImg} alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};
export default Home;
