import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import vercelImg from "../public/vercel.svg";
import { Button, ButtonBaseProps, Container } from "@mui/material";
import tw, { styled } from "twin.macro";
import MyButton from "../components/Mybutton";

export const getServerSideProps = async () => {
  const res = await fetch("http://localhost:3000/api/hello");
  const data = await res.json();
  if (!data) {
    return {
      notFound: true,
    };
  }
  return {
    props: data,
  };
};

const TailWindA = styled.a(() => [tw`text-5xl text-green-300 underline`]);

const Home: NextPage<{ name: string }> = ({ name }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div>
          <Button variant="text">Text Button</Button>
          <Button variant="contained">Contained Button</Button>
          <Button variant="outlined">Outlined Button</Button>
        </div>
        <div>
          <a tw="text-5xl text-red-500 underline">TailwindCss!</a>
        </div>
        <div>
          <MyButton>TailwindCss!</MyButton>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src={vercelImg} alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};
export default Home;
